### ISSUE TITLE
足跡、要望など

### ISSUE THREAD

**Issue by kikeroga3** [exrd/neteruhsp#1]
面白いものを作って下さり、ありがとうございます。

neteruhspをLinux(あるいはMac)にインストールしたいときに、私は何とかなりますが、
sudo wget ホニャララから始まるコマンド一覧のアホでも分かるインストール手順もどこかにあると
世間一般的にHSPライトユーザ的にはうれしいかもしれません。

いただいていきますm(_ _)m

**Comment by exrd** [comment]
あらら、まあ遊びで作った小物ですし、NYSLなのでお好きにどうぞ…。

> neteruhspをLinux(あるいはMac)にインストールしたいときに、私は何とかなりますが、
> sudo wget ホニャララから始まるコマンド一覧のアホでも分かるインストール手順もどこかにあると
> 世間一般的にHSPライトユーザ的にはうれしいかもしれません。

うーん、申し訳ないですが

- Linuxはディストリビューションも多く、使われているパッケージシステムも標準で入っているパッケージもまちまち
- そもそもLinux使いの人は最低限のことは分かる（はず）
- 何よりこのリポジトリはそういったものは目指してない

ので特にヘルプとかは書かないです。

> HSPCL版スタトレのワープコマンドの後で移動距離を入力するとこでエラーがでちゃいましたのでご報告です。

あーごめんなさい、実は誰もまだ触らないだろうと思って手元で修正してたバグとか抜けとかあげてませんでした。
ご指摘のものは d33da819793719055b2fb04baabe83fc28ed9aef で修正されてると思います。

**Comment by kikeroga3** [comment]
確かに。情報は十二分に載せてらっしゃいますし、要らないですね。
ちらっと思ったことをあまり考えずに書いてしまいました。申し訳ないです。
迅速な修正アップ、ありがとうございます！

**Comment by kikeroga3** [comment]
"neteruhsp_20170205.zip"いただきました。
あらためてスタトレ実行試しましたので、一応ご報告。

>CAPTAIN
>w
>WARP ENGINE
>SECTOR DISTANCE
>10
>COURSE (0-360)
>300
>ENTERPRISE IN Q-17 S-36
>KLINGON ATTACK
> -30 UNITS HIT FROM KLINGON AT S--30-45
>3948 UNITS OF ENERGY LEFT.
>CAPTAIN
>s
>ENTERPRISE IN Q-17 S-36
>SHORT RANGE SENSOR
>1 . . . . . . . .
>2 . . . . . . . .
>3 . . . . . E . .
>4 . . . . . . . .
>5 . . . . . . . .
>6 . . . . . . . .
>7 . . . . . . . .
>8 . . . . . . . .
>  1 2 3 4 5 6 7 8
>CAPTAIN
>l
>ENTERPRISE IN Q-17 S-36
>LONG RANGE SENSOR
>   0   0   0
>  13 308   3
>   9   9   2
>CAPTAIN

上記ログの
" -30 UNITS HIT FROM KLINGON AT S--30-45"の箇所はおそらく
正しくは
" 30 UNITS HIT FROM KLINGON AT S-30 Q-45"などど表示されるかと思います。

あとSHORT RANGE SENSORの結果ですが、
3隻いるはずのKLINGONが1隻も表示されないようです。

エラーで止まったりはしません。

以上です。

**Comment by exrd** [comment]
ﾔﾔ、なんかごめんなさい、滅茶苦茶バグってますね！；；（前回のリリースとか、実行できなかったと思いますし…）

流石に申し訳なくなってきたのでちゃんとデバッグとバグ修正をしました。
ひとまず怪しい、というかちゃんと動いてなかったとこはあらかた直ったかと思います。

ついでに自分でもスタトレちょっと遊んでみました。クリア…はできませんでしたが、無事ゲームオーバーまではいったので（最後にstop命令がないと怒られたりしましたが）、これでほぼほぼ大丈夫かなと思います。

まだ凝った書き方をするとパーサーからその後の意味解析周りがダメな気がしますが、サンプル提示して頂けたりしたら（＋このリポジトリで想定しているゴール内であれば、という条件付きですが）修正しようと思います。

**Comment by kikeroga3** [comment]
"neteruhsp_20170207.zip"を試し、スタトレをクリアしました。

>CAPTAIN
>r
>STATUS REPORT:
>STARDATE      3214
>TIME LEFT     16
>CONDITION     RED
>POSITION      Q-77 S-65
>ENERGY        1827
>TORPEDOES     8
>KLINGONS LEFT 1
>STARBASES     3
>CAPTAIN
>p
>PHASER
> ENERGIZED. UNITS TO FIRE
>1000
> 509 UNITS HIT KLINGON AT S-13 ***DESTROYED***
>
>
>MISSION ACCOMPLISHED.
>GOOD WORK...
>FANTASTIC!
>UNBELIEVABLE!
>4 KLINGONS IN 14 STARDATES. (280)
>0 CASUALTIES INCURRED. (100)
>YOUR SCORE:380
>
>ANOTHERE GAME? (Y OR N)

一通りのコマンドも使っておかしなところもなく問題なさそうです(^^)b

ありがとうございます。

クロスプラットフォームのお手軽インタプリタとして利用させていただきます。

**Comment by kikeroga3** [comment]
exrdさま
お世話になっております。
このたび「neteruhsp」から派生した「TinyHSP」をもとに作った「CuteHSP」の書籍が出ることになりました。

「CuteHSP」ではじめるプログラミング入門

「neteruhsp」が存在しなければこのような流れもなかったものと思います。
つきましてはささやかながらお礼としてこの書籍を謹呈さしあげたいのですが、送付先を教えていただけますでしょうか？

↓こちらまで
cutehsp＠outlook.jp

申し訳ないですが、ご連絡先がわからなかったのでこちらに書かせていただきました。
もしご不要でしたら削除ください。

**Comment by exrd** [comment]
このIssueは役割を終えたようなので閉じます。
